### PR TITLE
Update kernel to 4.4.78 and mark new packages for use

### PR DESCRIPTION
**Pull request by itskingori**
Because it has this patch:

* https://github.com/torvalds/linux/commit/d747a7a51b00984127a88113cdbbc26f91e9d815

Which solves this problem:

* https://github.com/moby/moby/issues/5618#issuecomment-286274811

See kernel CHANGELOG here (contains the patch):

* https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.4.78

### CODE REVIEW

**Comment by itskingori** [comment]
Related: https://github.com/kubernetes/kops/issues/2901#issuecomment-316352111.

**Comment by redbaron** [comment]
github archeology? :)

**Review by justinsb — APPROVED** [review]
LGTM

**Comment by justinsb** [comment]
Thanks @itskingori - a new image is long overdue :-)

I'm actually really impressed that you managed to figure this out!  Anything we should improve on the docs here?

**Comment by itskingori** [comment]
> Anything we should improve on the docs here?

@justinsb Ha! I was just about to ping you about this. There's a lot that's not obvious. I'll send a PR or two ... one for this part and for the image builder part.

**Pull request merged**
